### ISSUE TITLE
Yarn Start copying to wrong directory

### ISSUE THREAD

**Issue by javaadpatel** [LimeChain/etherlime-shape-react#2]
Hi,
I might be wrong because I am slightly new to React, but i noticed that the command in the package.json file: 
```"start": "etherlime compile --buildDirectory='./web/src/contracts' && cd web && react-scripts start" ```
did not create the Todo.json file in the web/src/contracts directory as it should, but instead created a whole new directory, see image below:
![image](https://user-images.githubusercontent.com/22832462/59599276-73c69d80-90fe-11e9-88d7-0d09bab72eeb.png)

I changed the command to:
```"start": "etherlime compile --buildDirectory=./web/src/contracts/ && cd web && react-scripts start"``` and now it creates it correctly under the /web/src/contracts folder. The only difference, is that i dropped the single qoutes around the directory path.

**Comment by desimira** [comment]
Hi, thank you for the issue. The problem may cause if you are using Windows OS. I've just removed the quotes and hope that fixes the problem.
